name       : perl-file-desktopentry
version    : '0.22'
release    : 7
source     :
    - http://search.cpan.org/CPAN/authors/id/M/MI/MICHIELB/File-DesktopEntry-0.22.tar.gz : 169c01e3dae2f629767bec1a9f1cdbd6ec6d713d1501e0b2786e4dd1235635b8
license    : Artistic-1.0-Perl
summary    : Perl module for interacting with .desktop files
component  : programming.perl
description: |
    Perl module for interacting with .desktop files
patterns   :
    - /usr/share/man
rundeps    :
    - perl-file-basedir
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
