name       : perl-file-desktopentry
version    : 0.08
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/M/MI/MICHIELB/File-DesktopEntry-0.08.tar.gz : 1e51b962f21fb9ce31df88210e305605f48f595845eed536c1f049cf0de09486
license    : Artistic-1.0-Perl
summary    : Perl module for interacting with .desktop files
description: |
    Perl module for interacting with .desktop files
patterns   :
    - /usr/share/man
setup      : |
    perl Makefile.PL PREFIX=/usr INSTALLDIRS=vendor DESTDIR=%installroot%
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/lib/perl5/5.20.1
